- name: Collect VM Metrics
  hosts: Env_Testing
  become: true
  gather_facts: true
  tasks:
    - name: Install systat(for mpstat)
      apt:
        name: sysstat
        state: present
      when: ansible_os_family=="Debian"

    - name: Install systat(For RedHat/Centos)
      yum:
        name: sysstat
        state: present
      when: ansible_os_family=="RedHat"

    - name: Get CPU Usage of the current machine
      shell: "mpstat 1 1 | awk '/Average/ && $NF ~ /[0-9.]+/ {printf(\"%.2f\n\", 100 - $NF)}'"
      register: cpu_usage

    - name: Get Memory Usage
      shell: "free | awk '/Mem/{printf(\"%.2f\n\", $3/$2 * 100.0)}'"
      register: mem_usage

    - name: Get Disk Usage
      shell: "df / | awk 'NR==2 {printf(\"%.2f\n\", $5)}' | tr -d '%'"
      register: disk_usage

    - name: Set Metrices Fact
      set_fact:
        vm_metrics:
          hostname: "{{ inventory_hostname }}" #hostaname like ec2-xx-xx-xx-xx.compute-1.amazonaws.com
          cpu: "{{ cpu_usage.stdout | float }}"
          mem: "{{ mem_usage.stdout | float }}"
          disk: "{{ disk_usage.stdout | float }}"
