plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  tag:Environment: Testing
  instance-state-name: running
compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ./client-key.pem
keyed_groups:
  - key: tags.name
    prefix: name
  - key: tags.Environment
    prefix: Env
